### ISSUE TITLE
Infinite error looping with farm cutscene triggers

### ISSUE THREAD

**Issue by minervamaga** [lisamreynolds/MusicalCellar#1]
Cross posting from Nexus, as it seems this issue has been reported previously and not addressed.  Upon exiting the farmhouse and triggering the mushroom/bat cave cutscene, the game enters a loop of errors regarding a cue name (one that does not exist in vanilla), soft locking the game until it crashes.  Easily reproducible and resolved by removing this mod.  Log here: https://smapi.io/log/38bdf4fbc8e14813a4dc559cd75317ba

**Comment by lisamreynolds** [comment]
Thank you! I was able to reproduce with the stray pet event and 1.1.1 should resolve it.
